apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: navigator
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
  mqDashboard: true
  replicas: 1
  storage:
    class: STORAGECLASS_FROM_OVERRIDES
  version: 2021.4.1
