apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-deployer-eventstreams-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - patch
      - get
      - delete
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - delete
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - operatorgroups
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - eventstreams.ibm.com
    resources:
      - eventstreams
    verbs:
      - get
      - create
      - patch
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get

