apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-integration-platform-navigator
  namespace: openshift-operators
  labels:
    operators.coreos.com/ibm-integration-platform-navigator.openshift-operators: ''
spec:
  channel: v7.0
  installPlanApproval: Automatic
  name: ibm-integration-platform-navigator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-integration-platform-navigator.v7.0.1
