apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-apiconnect
  labels:
    operators.coreos.com/ibm-apiconnect.eventendpointmanagement: ''
spec:
  channel: v5.0
  installPlanApproval: Automatic
  name: ibm-apiconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace

