apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-apiconnect
  labels:
    operators.coreos.com/ibm-apiconnect.eem: ''
spec:
  channel: v3.2
  installPlanApproval: Automatic
  name: ibm-apiconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-apiconnect.v3.2.0
