apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaUser
metadata:
  name: gateway-credentials-random
  labels:
    app.kubernetes.io/instance: es
    eventstreams.ibm.com/cluster: es
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: RANDOM.VALUES
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
