apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: stockprices-microsoft
  namespace: eventstreams
  labels:
    eventstreams.ibm.com/cluster: eem-demo-connectors
spec:
  class: "uk.co.dalelane.kafkaconnect.stockprices.StockPriceSourceConnector"
  tasksMax: 1
  config:
    #
    topic: STOCK.PRICES.MICROSOFT
    stock.symbol: MSFT
    #
    delay.hours: 168
    #
    alpha.vantage.api.key: ${file:/opt/kafka/external-configuration/alphavantage:apikey}
    #
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    #
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
