apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: random-values
  namespace: eventstreams
  labels:
    eventstreams.ibm.com/cluster: eem-demo-connectors
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  tasksMax: 1
  config:
    #
    topic: RANDOM.VALUES
    kafka.topic: RANDOM.VALUES
    #
    schema.filename: /opt/kafka/external-configuration/datagen-avro-schemas/randomvalues.avsc
    schema.keyfield: randomnumber
    #
    max.interval: 2000
    #
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    #
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
